export const vehicle = {
	FETCH_DATA: 'FETCH_VEHICLE_DATA',
	EDIT_DATA: 'EDIT_VEHICLE_DATA',
	RESET_DATA: 'RESET_VEHICLE_DATA',
};

export const dashboard = {
	FETCH_DATA: 'FETCH_DASHBOARD_DATA',
	EDIT_DATA: 'EDIT_DASHBOARD_DATA',
	RESET_DATA: 'RESET_DASHBOARD_DATA',
};

export const config = {
	EDIT_DATA: 'EDIT_CONFIG_DATA',
	RESET_DATA: 'RESET_CONFIG_DATA',
};
